name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - '**Dockerfile.*'
      - '**Dockerfile'
  workflow_dispatch:    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file  Dockerfile.env --tag erikluo/wantwordsenv:v1
    - name: Build the Docker image2
      run: docker build . --file  Dockerfile --tag erikluo/wantwords:v$(date +%Y%m%d)
    
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: push to dockerhub
      run: docker push erikluo/wantwordsenv:v1
    - name: push to dockerhub2
      run: docker push erikluo/wantwords:v$(date +%Y%m%d)
  