FROM ubuntu:18.04

# apt-get tencent source
# RUN echo "deb http://mirrors.tencent.com/ubuntu/ bionic main restricted universe multiverse \n" > /etc/apt/sources.list && \
#     echo "deb http://mirrors.tencent.com/ubuntu/ bionic-security main restricted universe multiverse \n" >> /etc/apt/sources.list && \
#     echo "deb http://mirrors.tencent.com/ubuntu/ bionic-updates main restricted universe multiverse \n" >> /etc/apt/sources.list && \
#     #echo "deb http://mirrors.tencent.com/ubuntu/ bionic-proposed main restricted universe multiverse \n" >> /etc/apt/sources.list && \
#     #echo "deb http://mirrors.tencent.com/ubuntu/ bionic-backports main restricted universe multiverse \n" >> /etc/apt/sources.list && \
#     echo "deb-src http://mirrors.tencent.com/ubuntu/ bionic main restricted universe multiverse \n" >> /etc/apt/sources.list && \
#     echo "deb-src http://mirrors.tencent.com/ubuntu/ bionic-security main restricted universe multiverse \n" >> /etc/apt/sources.list && \
#     echo "deb-src http://mirrors.tencent.com/ubuntu/ bionic-updates main restricted universe multiverse \n" >> /etc/apt/sources.list && \
#     #echo "deb-src http://mirrors.tencent.com/ubuntu/ bionic-proposed main restricted universe multiverse \n" >> /etc/apt/sources.list && \
#     #echo "deb-src http://mirrors.tencent.com/ubuntu/ bionic-backports main restricted universe multiverse\n" >> /etc/apt/sources.list && \
#     rm -rf /etc/apt/sources.list.d

# software version
ARG python=3
ENV PYTHON_VERSION=${python}
ENV LANG=zh_CN.UTF-8

RUN apt-get update && apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends \
        build-essential \
        pkg-config \
        locales \
        cmake \
        g++ \
        git \
        curl \
        vim \
        wget \
        strace \
        tcpflow \
        ca-certificates \
        libjpeg-dev \
        libpng-dev \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-dev \
        python${PYTHON_VERSION}-pip \
        python${PYTHON_VERSION}-distutils \
        python${PYTHON_VERSION}-setuptools \
        python${PYTHON_VERSION}-wheel \
        librdmacm1 \
        libibverbs1 \
        ibverbs-providers \
        iputils-ping \
        net-tools \
        ethtool \
        perl \
        lsb-release \
        iproute2 \
        telnet \
        pciutils \
        libnl-route-3-200 \
        kmod \
        libnuma1 \
        google-perftools \
        tmux \
        lsof && \
        rm -rf /rm -rf /var/lib/apt/lists/*

RUN sed -i -e 's/# zh_CN.UTF-8 UTF-8/zh_CN.UTF-8 UTF-8/' /etc/locale.gen && \
    echo 'LANG="zh_CN.UTF-8"'>/etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=zh_CN.UTF-8

COPY requirement.txt  /home/
RUN python3 -m pip install -r /home/requirement.txt


